In [1]:
import numpy as np

## array属性

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.shape

(2, 3)

In [4]:
arr.size

6

In [5]:
arr.ndim

2

## 创建array

In [6]:
arr1 = np.array([2,23,1],dtype = np.int64)
print(arr1)
print(arr1.dtype)

[ 2 23  1]
int64


In [7]:
arr1

array([ 2, 23,  1])

In [8]:
arr_zero = np.zeros((15,15))
arr_zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [9]:
arr_zero.dtype

dtype('float64')

In [10]:
arr_ones = np.ones((7,7))
arr_ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [11]:
arr_ones.dtype

dtype('float64')

In [12]:
arr_ones.size

49

In [13]:
arr_empties = np.empty((5,3))

In [14]:
arr_empties

array([[ 1.72723371e-077,  1.29074164e-231,  3.95252517e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  8.70018275e-313, -2.68679029e+154]])

In [15]:
arr_range = np.arange(10,22,2)
arr_range

array([10, 12, 14, 16, 18, 20])

In [16]:
arr_reshape = arr_range.reshape((2,3))

In [17]:
arr_range


array([10, 12, 14, 16, 18, 20])

In [18]:
arr_reshape

array([[10, 12, 14],
       [16, 18, 20]])

In [19]:
arr_linspace = np.linspace(1,10,11)
arr_linspace
# 不是线段，而是刻度
# linspace参数中第三个表示，앞두수를 포함한, 앞두수 사이의 모든 각도의 총수량

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

## numpy 基础运算

In [20]:
arr1

array([ 2, 23,  1])

In [21]:
arr2 = np.arange(10,16,2)

In [22]:
arr2

array([10, 12, 14])

In [23]:
arr2+arr1

array([12, 35, 15])

In [24]:
arr1*arr2

array([ 20, 276,  14])

In [25]:
arr1**arr2

array([             1024, 21914624432020321,                 1])

In [26]:
arr2

array([10, 12, 14])

In [27]:
arr_reshape>14

array([[False, False, False],
       [ True,  True,  True]])

In [28]:
arr3 = np.random.randn(3,3)

In [29]:
arr5 = np.random.randn(3,3)

In [30]:
arr3

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [31]:
arr5

array([[-0.17261656, -1.80608305,  0.0343997 ],
       [ 0.39223527, -0.5105568 , -0.42571994],
       [ 0.33480394,  1.43861877, -0.57195472]])

In [32]:
arr3.dot(arr5)
#  == np.dot(arr4,arr5)
#  矩阵运算，不理解。。。


array([[-0.76618582, -1.27677707,  1.44172454],
       [ 0.87921955,  1.58955274, -0.84842203],
       [ 0.5154929 ,  0.31262169, -0.29204828]])

In [33]:
arr_random = np.random.random((3,3))
arr_random
#  means any float number between zero and one. 

array([[0.93447859, 0.42156982, 0.34439709],
       [0.37414945, 0.43475222, 0.48280824],
       [0.00958303, 0.02096113, 0.77728279]])

In [34]:
arr3.max()

1.521087288348216

In [35]:
arr3
# axis중 1은 행 , 0은 열. 

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [36]:
arr3.min(axis = 1)

array([-2.23422086, -1.08221116, -0.99467092])

In [37]:
arr3.sum(axis = 0)

array([-3.01927142,  2.4084911 , -2.50100038])

In [38]:
np.random.randn(3,5)

array([[-1.52700516, -1.11972979, -0.10093925, -1.37432809, -0.22111596],
       [-0.20758864, -1.22387788, -0.14587767, -1.1985355 , -0.19955509],
       [ 0.62735016, -0.04698141,  0.44198055,  0.72504017,  0.04366871]])

In [39]:
np.random.rand(3,5)

array([[0.33148998, 0.6877014 , 0.06722339, 0.05088714, 0.3522738 ],
       [0.32994553, 0.7245987 , 0.64118047, 0.42980474, 0.70651218],
       [0.30364459, 0.42595504, 0.3411243 , 0.22703611, 0.11855475]])

In [40]:
np.random.randint(3,10,(3,3))

array([[5, 7, 7],
       [6, 3, 7],
       [8, 5, 4]])

## numpy 基础运算2

In [41]:
arr6 = np.arange(1,13)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr_average = arr6.reshape(3,4)
arr_average

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr_average.mean(0)

array([5., 6., 7., 8.])

In [44]:
np.argmin(arr_average)

0

In [45]:
np.argmax(arr_average)

11

In [46]:
np.median(arr_average)

6.5

In [47]:
np.cumsum(arr_average)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [48]:
np.diff(arr_average ,axis = False)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [49]:
arr_average!=0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
arr_average*30>200

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
arr3

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [52]:
np.sort(arr3, axis = False )

array([[-1.08221116, -0.46102913, -2.23422086],
       [-0.99467092,  1.34843295, -0.55288101],
       [-0.94238934,  1.52108729,  0.28610148]])

In [53]:
arr3

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [54]:
np.transpose(arr3)

array([[-0.94238934, -1.08221116, -0.99467092],
       [-0.46102913,  1.52108729,  1.34843295],
       [-2.23422086,  0.28610148, -0.55288101]])

In [55]:
np.clip(arr3, -0.1,1)

array([[-0.1       , -0.1       , -0.1       ],
       [-0.1       ,  1.        ,  0.28610148],
       [-0.1       ,  1.        , -0.1       ]])

## numpy索引

In [56]:
arr3

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [57]:
arr3.T

array([[-0.94238934, -1.08221116, -0.99467092],
       [-0.46102913,  1.52108729,  1.34843295],
       [-2.23422086,  0.28610148, -0.55288101]])

In [58]:
arr3.transpose()

array([[-0.94238934, -1.08221116, -0.99467092],
       [-0.46102913,  1.52108729,  1.34843295],
       [-2.23422086,  0.28610148, -0.55288101]])

In [59]:
arr3

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [60]:
arr3[2][1]

1.3484329461473878

In [61]:
arr3[1,1]

1.521087288348216

In [62]:
arr3[1:3,1:3]

array([[ 1.52108729,  0.28610148],
       [ 1.34843295, -0.55288101]])

In [63]:
for col in arr3.T:
    print(col)

[-0.94238934 -1.08221116 -0.99467092]
[-0.46102913  1.52108729  1.34843295]
[-2.23422086  0.28610148 -0.55288101]


In [64]:
x = np.arange(0,15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
y = x.reshape(5,3)
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [66]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
x == y.flatten()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [68]:
A = np.array([2,3,4])
A

array([2, 3, 4])

In [70]:
A.T

array([2, 3, 4])

In [77]:
arr3

array([[-0.94238934, -0.46102913, -2.23422086],
       [-1.08221116,  1.52108729,  0.28610148],
       [-0.99467092,  1.34843295, -0.55288101]])

In [75]:
arr3.shape

(3, 3)

In [80]:
B = np.array([[5,6,7],[8,9,10]])
B

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [81]:
B.shape

(2, 3)

In [82]:
A

array([2, 3, 4])

In [87]:
C = A[np.newaxis,:]

In [86]:
A.shape

(3,)

In [88]:
C.shape

(1, 3)